In [3]:
### Identify the number is positive,negative or zero
a=int(input("Enter the number "))
if a < 0:
    print("the number is negative.")
elif a >0:
    print("the number is positive")
else:
    print("the number is zero")

Enter the number 0
the number is zero

In [9]:
### check the number whether the number is odd or even
a=int(input("Enter the number "))
if (a%2)== 0:
    print("the number is even")
else:
    print("the number is odd")

Enter the number -88
the number is even

In [15]:
### check whether the year is leap year or not.
a=int(input("Enter the year "))
if(a%4 ==0):
    print("the given year is a leap year.")
else:
    print("the given year isnot a leap year")

Enter the year 2000
the given year is a leap year.

In [47]:
### check whether the number is prime number or not
a=int(input("Enter the number "))
status=0
if a > 1:
    for i in range(2,a):
        if (a%i)==0:
            status=1
            break
    if (status == 0):
        print("true")
    else:
        print("false")
else:
    print("false")

Enter the number 45
false

In [52]:
### print the prime numbers between 1-10000
for number in range (1, 1000):  
    if number > 1:  
        for i in range (2, number):  
            if (number % i) == 0:  
                break  
        else:  
            print (number)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997